/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cbox_MainLib */

#ifndef _Included_com_cbox_MainLib
#define _Included_com_cbox_MainLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cbox_MainLib
 * Method:    initialize
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_cbox_MainLib_initialize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_cbox_MainLib
 * Method:    testMethod
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_cbox_MainLib_testMethod
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_cbox_MainLib
 * Method:    androidReceive
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_cbox_MainLib_androidReceive
  (JNIEnv *, jobject, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
