######################################################################
# Automatically generated by qmake (2.01a) Sat May 7 12:45:01 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ZcDbBindings.h
SOURCES += main.cpp

CONFIG += qt
QT += sql
