all: 
	g++ CConnectivity.cpp  StringFunctions.cpp StringFunctions.h NetVisible.cpp NetVisible.h WifiListener.h WifiListener.cpp NetReceiver.cpp NetReceiver.h NetTransmiter.cpp NetTransmiter.h -lpthread -o Debug/run
