all: 
	g++ CConnectivity.cpp  BlueUnit.h BlueUnit.cpp StringFunctions.cpp StringFunctions.h NetVisible.cpp NetVisible.h WifiListener.h WifiListener.cpp NetReceiver.cpp NetReceiver.h NetTransmiter.cpp NetTransmiter.h -fpermissive -lpthread -lbluetooth  -o Debug/run
