/*define parameteres that zeroconf needs to work*/
#define TYPE_QUESTION 1
#define TYPE_RESPONSE 2
#define TYPE_NET 3
#define OUTSIDER_IP "0.0.0.0"
#define IN_NETWORK 0
#define WANT_NETWORK 1
#define HOSTNAME_LEN 20
#define TYPE_PROB_HOSTNAME 4
#define NUMBER_OF_ROWS 6
#define NUM_STRUCTS 10
#define PARTICIPATE "part"
#define WELCOME "welc"
#define HELLO "hell"
#define ADVERTISE "adve"
#define QUERY "quer"
#define LEAVING "leav"
#define zeroPING "ping"
#define zeroPONG "pong"
#define QUERY_LEN 10
#define NUM_ANSWERS 2
#define TYPE_LEN 5
