/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cbox_WiseLib */

#ifndef _Included_com_cbox_WiseLib
#define _Included_com_cbox_WiseLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cbox_WiseLib
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_cbox_WiseLib_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
