/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cbox_WiseLib */

#ifndef _Included_com_cbox_WiseLib
#define _Included_com_cbox_WiseLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cbox_WiseLib
 * Method:    androidSend
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cbox_WiseLib_androidSend
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
