/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cbox_WiseLib */

#ifndef _Included_com_cbox_WiseLib
#define _Included_com_cbox_WiseLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cbox_WiseLib
 * Method:    androidInitModel
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_cbox_WiseLib_androidInitModel
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_cbox_WiseLib
 * Method:    androidSend
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_cbox_WiseLib_androidSend
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_cbox_WiseLib
 * Method:    androidReceive
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_cbox_WiseLib_androidReceive
  (JNIEnv *, jobject, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
