/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ceid_ds2_cbox_helloandroid_NativeConnection */

#ifndef _Included_ceid_ds2_cbox_helloandroid_NativeConnection
#define _Included_ceid_ds2_cbox_helloandroid_NativeConnection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ceid_ds2_cbox_helloandroid_NativeConnection
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ceid_1ds2_cbox_helloandroid_NativeConnection_stringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
