/******************************************************************************
* This file is part of cbox.
* 
* cbox is free software: you can redistribute it and/or modify
* it under the terms of the GNU LesserGeneral Public License as published
* by the Free Software Foundation, either version 3 of the License, or
* any later version.
* 
* Cbox is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU Lesser General Public License for more details.
* 
* You should have received a copy of the GNU Lesser General Public License
* along with cbox.  If not, see <http://www.gnu.org/licenses/>.
*******************************************************************************/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ceid_ds2_cbox_helloandroid_NativeConnection */

#ifndef _Included_ceid_ds2_cbox_helloandroid_NativeConnection
#define _Included_ceid_ds2_cbox_helloandroid_NativeConnection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ceid_ds2_cbox_helloandroid_NativeConnection
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ceid_1ds2_cbox_helloandroid_NativeConnection_stringFromJNI(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
