/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ceid_ds2_cbox_templateAndroid_CalcNativeClass */

#ifndef _Included_ceid_ds2_cbox_templateAndroid_CalcNativeClass
#define _Included_ceid_ds2_cbox_templateAndroid_CalcNativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ceid_ds2_cbox_templateAndroid_CalcNativeClass
 * Method:    calcsFromJNI
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ceid_1ds2_cbox_templateAndroid_CalcNativeClass_calcsFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     ceid_ds2_cbox_templateAndroid_CalcNativeClass
 * Method:    playWithTemplateJNI
 * Signature: (IIDD)D
 */
JNIEXPORT jdouble JNICALL Java_ceid_1ds2_cbox_templateAndroid_CalcNativeClass_playWithTemplateJNI
  (JNIEnv *, jobject, jint, jint, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
